// <auto-generated />
namespace PhantomNet.Searching.Entities
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("PhantomNet.Searching.Entities.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// Store does not implement IEagerLoadingEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string StoreNotIEagerLoadingEntityStore
        {
            get { return GetString("StoreNotIEagerLoadingEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IEagerLoadingEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotIEagerLoadingEntityStore()
        {
            return GetString("StoreNotIEagerLoadingEntityStore");
        }

        /// <summary>
        /// Store does not implement IQueryableEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string StoreNotIQueryableEntityStore
        {
            get { return GetString("StoreNotIQueryableEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IQueryableEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotIQueryableEntityStore()
        {
            return GetString("StoreNotIQueryableEntityStore");
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
